services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env.local
    depends_on:
      # - backend
      - mysql

  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: task_manager
      MYSQL_USER: nextek
      MYSQL_PASSWORD: nex@Tek
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

